export const types = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    ADD_CHANNEL: 'ADD_CHANNEL',
    REMOVE_CHANNEL: 'REMOVE_CHANNEL',
    SEND_MESSAGE: 'SEND_MESSAGE',
    SEND_DUMMY_MESSAGE: 'SEND_DUMMY_MESSAGE',
    PAGE_CHAT_RELOAD: 'PAGE_CHAT_RELOAD'
};
